# .github/workflows/deploy.yml

name: Deploy Frontend to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          # This is correct - keeps the Node.js version compatible with Vite
          node-version: '20'

      - name: Install Dependencies
        # REMOVED: 'working-directory' is not needed because package.json is at the root
        run: npm install

      - name: Build React App
        # REMOVED: 'working-directory' is not needed here either
        run: VITE_API_URL=https://api.zemaydar.online/api npm run build
        
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          
          # CHANGED: The 'dist' folder is now at the root of the checkout
          local-dir: ./dist/ 
          
          # This remains correct - your main domain's web root
          server-dir: /public_html/
          
          # This option ensures a clean deployment every time
          dangerous-clean-slate: true